kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kup
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /data/provision
    containerPath: /var/local-path-provisioner
  - hostPath: /data
    containerPath: /data
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
